//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardTokenizationAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCredential
    {
        public int ClientID { get; set; }
        public string ClientName { get; set; }
        public string ClientDescription { get; set; }
        public string ClientPassword { get; set; }
        public string ClientSecret { get; set; }
    }
}
